server:
  port: 8007
spring:
  application:
    name: api-usual
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大空闲数，数据库连接的最大空闲时间。超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
        max-idle: 0
        #连接池的最大数据库连接数。设为0表示无限制
        max-Active: 8
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        max-Wait: 1ms

